### ISSUE TITLE
Call original function?

### ISSUE THREAD

**Issue by jacksgt** [cppcoffee/inl_hook#1]
Hi,

first of all: thank you for this cool and easy to use library!

The examples in hello_core.c currently shows how to completely replace a function. Is it also possible to execute the original function after running the injected code? If so, how?

Regards
Jack

**Comment by cppcoffee** [comment]
Hi,

It can't execute the original function after running the injected code!!! because the original function is used intel JMPF instructions, call original function will cause RSP mistaken.  can consider use CALLF instructions replace JMPF instructions.

So example code not calls the original function.

Think

**Comment by jacksgt** [comment]
Ok, so executing the code in the original function is not supported with this library.

Thanks for answering my question.

**Comment by cppcoffee** [comment]
https://www.slideshare.net/ennael/kernel-recipes-2019-ftrace-where-modifying-a-running-kernel-all-started

call_rcu_tasks
